FROM eclipse-temurin:17-jdk-alpine
MAINTAINER "rocky@rockycorp.com"
COPY target/springboot-currency-exchange-service-0.0.1-SNAPSHOT.jar currency-exchange-service-0.0.1.jar
ENTRYPOINT ["java","-jar","/currency-exchange-service-0.0.1.jar"]